### ISSUE TITLE
Track original script

### ISSUE THREAD

**Issue by dnebauer** [parisni/msmtp-queue-scheduler#1]
In the 4 years since you created this fork the [original project](https://git.marlam.de/gitweb/?p=msmtp.git;a=shortlog) has gone from version 1.8.0 to 1.8.22. This includes significant changes to the `msmtpq` script, including inheriting environmental variables for the script's 3 key variables and changing those variable names to avoid collisions with other projects.

Is there any chance of a one-off upgrade of your fork to track the [original project](https://github.com/marlam/msmtp-mirror)? It would be even better to know your fork will continue to be updated to incorporate changes in the original project.

**Comment by parisni** [comment]
Thanks for your interest . I don't maintain/use it anymore. Feel free to backport this to the main repository if this is of interest
